### ISSUE TITLE
issue about msc_glm_eval.sh

### ISSUE THREAD

**Issue by NLP-hua** [leolee99/LD-Agent#2]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from DataLoader.MSC import MSC
  File "/home/USER/LD-Agent-main/DataLoader/MSC.py", line 7, in <module>
    from nlgeval import calc_nlg_metrics
  File "/home/USER/LD-Agent-main/nlgeval/__init__.py", line 8, in <module>
    from metric import NLGEval
ModuleNotFoundError: No module named 'metric'

**Comment by Syuchin** [comment]
Please check if the metric has been downloaded, as it has already been written in the readme.md.
